# Configure main menu and social menu
main:
 - identifier: "categories"
   name: "Category"
   url: "/categories"
   weight: 2
   params:
     icon: "categories"
     newtab: false

social:
  - identifier: "github"
    name: "GitHub"
    url: "https://github.com/swellful/swellful.github.io"
    params:
      icon: "brand-github"
  
  - identifier: "twitter"
    name: "Twitter"
    url: "https://twitter.com"
    params:
      icon: "brand-twitter"