# Configure main menu and social menu
#main:
#  - identifier: "home"
#    name: "Home"
#    url: "/"
#    params:
#      icon: "home"
#      newtab: true

social:
  - identifier: "github"
    name: "GitHub"
    url: "https://github.com/swellful/swellful.github.io"
    params:
      icon: "brand-github"
  
  - identifier: "twitter"
    name: "Twitter"
    url: "https://twitter.com"
    params:
      icon: "brand-twitter"