# Pages placed under these sections will be shown on homepage and archive page.
mainSections:
  - post
# Output page's full content in RSS.
rssFullContent: true
favicon: /favicon.png

footer:
  since: 2025
  customText: ""

dateFormat:
  published: "Jan 02, 2006"
  lastUpdated: "Jan 02, 2006 15:04 MST"

sidebar:
  emoji: "🏄‍♂️"
  subtitle: "The pattern reveals itself — not now, perhaps, but always."
  avatar:
    enabled: true
    local: true
    src: img/avatar.png

article:
  headingAnchor: false
  math: false
  readingTime: true
  license:
    enabled: true
    default: "© 2025 Swellful. All rights reserved."

# Widgets
widgets:
  homepage:
    - type: search
    
    - type: archives
      params:
        limit: 5
    
    - type: categories
      params:
        limit: 10
    
    - type: tag-cloud
      params:
        limit: 10
  
  page:
    - type: toc

opengraph:
  twitter:
    site: ""
    card: "summary_large_image"

defaultImage:
  opengraph:
    enabled: false
    local: false
    src: ""

colorScheme:
  toggle: true
  default: auto

imageProcessing:
  cover:
    enabled: true
  content:
    enabled: true

# Comments
comments:
  enabled: true
  provider: giscus
  giscus:
    repo: "swellful/swellful.github.io"
    repoID: "R_kgDOOi8nMw"
    category: "Comments"
    categoryID: "DIC_kwDOOi8nM84Cpyyb"
    mapping: "pathname"
    lightTheme: ""
    darkTheme: ""
    reactionsEnabled: 1
    emitMetadata: 0